version: '3'

services:
    database:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=adminpw1
            - MYSQL_DATABASE=whoamiproject
            - MYSQL_ROOT_PASSWORD=adminpw1
            - MYSQL_ROOT_HOST=% # allows non-docker accesses
    backend:
        build: ./backend
        environment:
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=adminpw1
            - MYSQL_HOST=database
            - MYSQL_PORT=3306
        ports:
            - "8000:8000"
        links:
            - database
